name: at_editor
description: AI-powered photo editor with 8K upscale
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  dio: ^5.4.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  gallery_saver: ^2.3.2
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1

flutter:
  uses-material-design: true
